fix: Report test name that fails to parse sender address
risechain/pevm pull request #364
Opened 2024-09-29 18:27 UTC by varun-doshi

Closes https://github.com/risechain/pevm/issues/326

Changes:
Function `build_tx_env` now requires a parameter `path`

2024-09-29 18:33 UTC, hai-rise requested changes
CI is failing with some nit comments 🙏.

2024-09-29 18:33 UTC, hai-rise commented on tests/ethereum/main.rs
> +fn build_tx_env(tx: &TransactionParts, indexes: &TxPartIndices, path: &Path) -> Result<TxEnv, ParseError> {
Nit but can you put `path` as the first parameter 🙏?

2024-09-29 18:33 UTC, hai-rise commented on tests/ethereum/main.rs
> +            panic!("Failed to parse caller.{}",path);
`Failed to parse caller for {path:?}` is better?

2024-09-29 18:33 UTC, hai-rise commented on tests/ethereum/main.rs
> +            let tx_env = build_tx_env(&unit.transaction, &test.indexes,path);
Let's add a space after the `,` as well.

2024-09-29 19:46 UTC, varun-doshi commented
Resolved the above comments

2024-09-30 00:25 UTC, hai-rise approved these changes
This is nice, thank you!

2024-09-30 00:25 UTC, merged