refactor: add error handling for Bytecode type
risechain/pevm pull request #379
Opened 2024-10-14 10:26 UTC by TropicalDog17

Fixes #378

2024-10-14 10:26 UTC, TropicalDog17 commented
\cc @hai-rise

2024-10-14 10:53 UTC, TropicalDog17 commented
Seem the tests is falling, I will try to fix asap @hai-rise

2024-10-14 10:55 UTC, hai-rise commented
@TropicalDog17 Yes, conversions in the main library must also handle the new `Result`. Thank you for working on this  🙏!

2024-10-15 07:40 UTC, TropicalDog17 commented
Hi @hai-rise, seems CI is passing now, can you take a look :)

2024-10-15 12:19 UTC, hai-rise requested changes
I've left some comments. Some parts can be quite confusing. We should definitely improve error handling going forward!

2024-10-15 12:19 UTC, hai-rise commented on src/storage.rs
> +                .map(|c| Bytecode::try_from(c).unwrap_or_default())
This falls back to a default bytecode on conversion error which seems quite dangerous. I suppose we'd need something like this:
```rust
enum StorageWrapperError<S: Storage> {
    StorageError(S::Error),
    InvalidBytecode(BytecodeConversionError),
}
```

Then `type Error = StorageWrapperError<S>;` for proper error-handling.

2024-10-15 12:19 UTC, hai-rise commented on src/storage.rs
> +        let basic = self.0.basic(&address)?;
Perhaps just flatten it to this?
```rust
let Some(basic) = self
    .0
    .basic(&address)
    .map_err(StorageWrapperError::StorageError)?
else {
    return Ok(None);
};
```

2024-10-16 08:44 UTC, hai-rise requested changes
More nits :pray:.

2024-10-16 08:44 UTC, hai-rise commented on Cargo.toml
> +thiserror = "1.0.64"
Let's put this under `smallvec`.

2024-10-16 08:44 UTC, hai-rise commented on src/storage.rs
> +/// Errors when wrapping storage.
`/// revm [Database] errors when using pevm [Storage] as the underlying provider.`

2024-10-16 08:44 UTC, hai-rise commented on src/storage.rs
> +                    let code_hash = self.0.code_hash(&address).ok().flatten();
Storage errors should be returned instead of defaulting to a `None` here.

2024-10-16 08:44 UTC, hai-rise commented on src/storage.rs
> +                        .and_then(|hash| self.0.code_by_hash(&hash).ok().flatten())
Storage errors should be returned instead of defaulting to a `None` here.

2024-10-16 08:44 UTC, hai-rise commented on src/storage.rs
> +                                .unwrap_or_default()
We must return the error, not defaulting after mapping it!

2024-10-16 08:44 UTC, hai-rise commented on src/vm.rs
> +    /// The bytecode is invalid and cannot be converted.
Nit but can you put this above `InvalidMemoryValueType`?

2024-10-16 08:45 UTC, hai-rise commented on src/storage.rs
> +        let dangling_data = bytes!("010203").to_vec();
@TropicalDog17 You may have missed this as it was hidden by GitHub!

2024-10-16 12:03 UTC, hai-rise requested changes
Almost there!

2024-10-16 15:36 UTC, TropicalDog17 commented on src/storage.rs
> +        eof_dangling.extend(dangling_data);
yeah pretty sure I've fixed this

2024-10-16 16:30 UTC, hai-rise approved these changes
Thank you for your patience! Hopefully, #382 will also remove most of these complications in the future.

2024-10-16 16:30 UTC, merged

2024-10-17 02:18 UTC, TropicalDog17 commented
> Thank you for your patience! Hopefully, #382 will also remove most of these complications in the future.

Yeah I'm also very appreciated your detailed review @hai-rise